### ISSUE TITLE
Add a fork me on github ribbon/banner

### ISSUE THREAD

**Issue by atomtigerzoo** [atomtigerzoo/launchcontrol#1]
**This is a nice task for beginners or people with little time wanting to contribute in [Hacktoberfest](https://hacktoberfest.digitalocean.com/)! 🎃 👻**

**- What's the task?**

The projects website https://atomtigerzoo.github.io/launchcontrol/ should contain a "Fork me on github" banner like the ones shown here: https://github.com/blog/273-github-ribbons

**Extra points** for creating a graphic yourself with the text _"Contribute on github"_ 💯

Have fun & thank you! 🎉

**Comment by ypahalajani** [comment]
@atomtigerzoo : I'm up for this!

**Comment by anujagrazzel** [comment]
@atomtigerzoo  I wanna work on this!!!

**Comment by atomtigerzoo** [comment]
First come, first serve I would say - maybe one could implement the standard banner and the second could then integrate the custom message of "Contribute on github"? 👍  Just do your pull request if you would like to solve the issue 😺

**Comment by dilum1995** [comment]
I also wanna contribute on this

**Comment by ypahalajani** [comment]
@atomtigerzoo: I had implemented this but, I was seeing @anujagrazzel's PR and thought, let this be merged and then, I'll see for any improvements based on the semantics of HTML or CSS missing in code implementation. Let me know, what you think about it?

**Comment by atomtigerzoo** [comment]
Thank you everyone for your contributions! 👍 
I liked rajeevdesai PR the most and it fitted best, so I took his PR, improved it a little and merged it. Don't be sad that it wasn't your PR that got merged. It is not lost for the Hacktoberfest challenge :)
